<<<<<<< HEAD
version: '2'
=======
version: '3'
>>>>>>> origin/master

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    privileged: true
<<<<<<< HEAD
=======
    restart: always
>>>>>>> origin/master
    ports:
      - 80:80
      - 443:443
    volumes:
<<<<<<< HEAD
      - /home/wordpress-on-docker/nginx-proxy/docker-compose.d/certs:/etc/nginx/certs:ro
      - /home/wordpress-on-docker/nginx-proxy/docker-compose.d/htpasswd:/etc/nginx/htpasswd
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/wordpress-on-docker/nginx-proxy/nginx.conf:/etc/nginx/conf.d/my_proxy.conf
    restart: always
=======
      - ./current/public:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/conf.d/my_proxy.conf
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
>>>>>>> origin/master
    networks:
      - common_link

  letsencrypt-nginx:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx
<<<<<<< HEAD
=======
    restart: always
>>>>>>> origin/master
    privileged: true
    volumes:
      - /home/wordpress-on-docker/nginx-proxy/docker-compose.d/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
<<<<<<< HEAD
    volumes_from:
      - nginx-proxy
    restart: always
    networks:
      - common_link
=======
    volumes:
      - ./current/public:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/conf.d/my_proxy.conf
    networks:
      - common_link
volumes:
  vhost:
>>>>>>> origin/master
networks:
  common_link:
    external: true
